name: Merge App
'on':
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
      - name: Install dependencies
        run: npm ci
      - name: Run ESLint
        run: npm run lint:scripts
      - name: Run Stylelint
        run: npm run lint:styles
      - name: Build
        run: npm run build
      - name: Test
        run: npm test
      - name: E2E tests
        uses: cypress-io/github-action@v2
        with:
          command: npm run cypress:run
          start: npm run dev
          wait-on: http://localhost:3000
